require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'
install! 'cocoapods', :deterministic_uuids => false

production = ENV["PRODUCTION"] == "1"

target 'vividusTestApp' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    :flipper_configuration => FlipperConfiguration.enabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )


  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  pod 'RNCClipboard', :path => '../node_modules/@react-native-community/clipboard'

  target 'vividusTestAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    flipper_post_install(installer)

    installer.pods_project.targets.each do |target|
      if target.name == "React-Core.common-AccessibilityResources"
        target.remove_from_project
      end
    end

    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'vividusTestApp-tvOS' do
  # Pods for vividusTestApp-tvOS

  target 'vividusTestApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
