desc 'Build Android App'
lane :build_android do |options|
  gradle(
    task: 'clean',
    project_dir: './android'
  )

  gradle(
    task: 'assemble',
    build_type: 'Release',
    project_dir: './android'
  )

  archiveApp(
    path: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}",
    platform: 'android',
    release_version: options[:release_version]
  )
end

desc 'Build iOS App'
lane :build_ios do |options|
  sh(
    command: 'cd ../ios && pod install'
  )

  build_app(
    workspace: './ios/vividusTestApp.xcworkspace',
    scheme: 'vividusTestApp',
    clean: true,
    skip_package_ipa: true,
    sdk: 'iphonesimulator',
    destination: 'generic/platform=iOS Simulator',
    skip_codesigning: true,
    build_path: 'build'
  )

  sh(
    command: 'cd ../build && \
              find . -name "*app" -type d -exec cp -r {} . \;'
  )

  archiveApp(
    path: '../build/vividusTestApp.app',
    platform: 'ios',
    release_version: options[:release_version]
  )
end

private_lane :archiveApp do |options|
  sh(
    command: "readonly APP_NAME=$(basename #{options[:path]}) && \
              cp -r #{options[:path]} $APP_NAME && \
              readonly APP=vividus-test-app-#{options[:platform]}-#{options[:release_version]}.zip && \
              zip -r $APP $APP_NAME"
  )
end
