name: Vividus App CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install npm dependencies
        run: |
          npm install
      
      - name: Run lint
        run: |
          npm run lint

      - name: Run test
        run: |
          npm run test
