name: Vividus Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '* 2 * * 6'

env:
  RELEASE_VERSION: 0.3.0

jobs:
  params:
    name: Parse environments variables
    runs-on: ubuntu-latest
    outputs:
      params: ${{ steps.env-vars.outputs.params }}
    steps:
      - name: install jq
        run: pip install jq
      - id: env-vars
        name: Output environment variables
        run: echo "::set-output name=params::$(echo $(jq -n 'env'))"

  saucelabs-upload-by-schedule:
    if: github.event_name == 'schedule'
    needs: [ params ]
    name: SauceLabs Storage Upload by Scheduler
    uses: ./.github/workflows/saucelabs-upload.yml
    with:
      release-version: ${{ fromJson(needs.params.outputs.params).RELEASE_VERSION }}
    secrets: inherit
  
  android-ci:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs: [ params ]
    name: Android App CI
    uses: ./.github/workflows/android-ci.yml
    with:
      release-version: ${{ fromJson(needs.params.outputs.params).RELEASE_VERSION }}
    secrets: inherit

  ios-ci:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    needs: [ params ]
    name: iOS App CI
    uses: ./.github/workflows/ios-ci.yml
    with:
      release-version: ${{ fromJson(needs.params.outputs.params).RELEASE_VERSION }}
    secrets: inherit
  
  saucelabs-upload:
    if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
    needs: [ android-ci, ios-ci, params ]
    name: SauceLabs Storage Upload
    uses: ./.github/workflows/saucelabs-upload.yml
    with:
      release-version: ${{ fromJson(needs.params.outputs.params).RELEASE_VERSION }}
    secrets: inherit
